# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62452f69955f67c8204e566da60b40bd6e33cba826d1742a9de73eda08caa1310539daec2455fa650d89d6857f9ba84c6bf2020d9ee6a2c90429b56669d17543

test:
  secret_key_base: befb0446dcd58963ac1658e01a0a39e53dc7def9fb73a2be8e2016137549dbc3e87132cce779ee1db32434747e9a5d4bb0e5b8d7741375b4a2b837b55a6afdd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
